// <auto-generated />
using System;
using FIM.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIM.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427082018_UserVotesPostId")]
    partial class UserVotesPostId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIM.Server.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ForumPostId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("UpVotes")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FIM.Server.Models.ForumPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tag")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ForumPosts");
                });

            modelBuilder.Entity("FIM.Server.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FIM.Server.Models.Print", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstimatedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("GramsUsed")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SpoolId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SpoolId");

                    b.ToTable("Prints");
                });

            modelBuilder.Entity("FIM.Server.Models.PublicFilamentCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedTemp")
                        .HasColumnType("int")
                        .HasJsonPropertyName("bed_temp");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("manufacturer");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasJsonPropertyName("color_hex");

                    b.PrimitiveCollection<string>("ColorHexes")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("color_hexes");

                    b.Property<double>("Diameter")
                        .HasColumnType("float")
                        .HasJsonPropertyName("diameter");

                    b.Property<int?>("ExtruderTemp")
                        .HasColumnType("int")
                        .HasJsonPropertyName("extruder_temp");

                    b.Property<string>("Finish")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasJsonPropertyName("finish");

                    b.Property<bool>("Glow")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("glow");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasJsonPropertyName("material");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasJsonPropertyName("name");

                    b.Property<bool>("Translucent")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("translucent");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasJsonPropertyName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ColorHex")
                        .HasDatabaseName("IX_PublicFilament_ColorHex");

                    b.HasIndex("Diameter")
                        .HasDatabaseName("IX_PublicFilament_Diameter");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_PublicFilament_Id");

                    b.HasIndex("Material")
                        .HasDatabaseName("IX_PublicFilament_Material");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_PublicFilament_Name");

                    b.HasIndex("ColorHex", "Id")
                        .HasDatabaseName("IX_PublicFilament_Sort_ColorHex");

                    b.HasIndex("Diameter", "Id")
                        .HasDatabaseName("IX_PublicFilament_Sort_Diameter");

                    b.HasIndex("Material", "Id")
                        .HasDatabaseName("IX_PublicFilament_Sort_Material");

                    b.HasIndex("Name", "Id")
                        .HasDatabaseName("IX_PublicFilament_Sort_Name");

                    b.ToTable("PublicFilamentCatalogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_PublicFilament_BedTemp_Range", "[BedTemp] IS NULL OR ([BedTemp] >= 0 AND [BedTemp] <= 200)");

                            t.HasCheckConstraint("CK_PublicFilament_Diameter_Range", "[Diameter] > 0 AND [Diameter] <= 10");

                            t.HasCheckConstraint("CK_PublicFilament_ExtruderTemp_Range", "[ExtruderTemp] IS NULL OR ([ExtruderTemp] >= 0 AND [ExtruderTemp] <= 500)");

                            t.HasCheckConstraint("CK_PublicFilament_Weight_Positive", "[Weight] > 0");
                        });
                });

            modelBuilder.Entity("FIM.Server.Models.Spool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedTemp")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorHex")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ColorHexes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<int?>("ExtruderTemp")
                        .HasColumnType("int");

                    b.Property<bool>("Favorite")
                        .HasColumnType("bit");

                    b.Property<string>("Finish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Glow")
                        .HasColumnType("bit");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RemainingWeight")
                        .HasColumnType("float");

                    b.Property<decimal>("SpoolCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("TotalWeight")
                        .HasColumnType("float");

                    b.Property<bool>("Translucent")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spools");
                });

            modelBuilder.Entity("FIM.Server.Models.UserFavoriteFilament", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FilamentId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FilamentId");

                    b.HasIndex("FilamentId");

                    b.ToTable("UserFavoriteFilaments");
                });

            modelBuilder.Entity("FIM.Server.Models.UserVotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserVotes");
                });

            modelBuilder.Entity("FIM.Server.Models.Print", b =>
                {
                    b.HasOne("FIM.Server.Models.Spool", "Spool")
                        .WithMany()
                        .HasForeignKey("SpoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spool");
                });

            modelBuilder.Entity("FIM.Server.Models.UserFavoriteFilament", b =>
                {
                    b.HasOne("FIM.Server.Models.PublicFilamentCatalog", "Filament")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("FilamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filament");
                });

            modelBuilder.Entity("FIM.Server.Models.PublicFilamentCatalog", b =>
                {
                    b.Navigation("FavoritedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
