// <auto-generated />
using System;
using FIM.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIM.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326085047_UserFavoriteFilaments")]
    partial class UserFavoriteFilaments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIM.Server.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FIM.Server.Models.Print", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstimatedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("GramsUsed")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SpoolId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpoolId");

                    b.ToTable("Prints");
                });

            modelBuilder.Entity("FIM.Server.Models.PublicFilamentCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedTemp")
                        .HasColumnType("int")
                        .HasJsonPropertyName("bed_temp");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("manufacturer");

                    b.Property<string>("ColorHex")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("color_hex");

                    b.PrimitiveCollection<string>("ColorHexes")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("color_hexes");

                    b.Property<double>("Diameter")
                        .HasColumnType("float")
                        .HasJsonPropertyName("diameter");

                    b.Property<int?>("ExtruderTemp")
                        .HasColumnType("int")
                        .HasJsonPropertyName("extruder_temp");

                    b.Property<string>("Finish")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("finish");

                    b.Property<bool>("Glow")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("glow");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("material");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<bool>("Translucent")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("translucent");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasJsonPropertyName("weight");

                    b.HasKey("Id");

                    b.ToTable("PublicFilamentCatalogs");
                });

            modelBuilder.Entity("FIM.Server.Models.Spool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedTemp")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorHex")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ColorHexes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<int?>("ExtruderTemp")
                        .HasColumnType("int");

                    b.Property<bool>("Favorite")
                        .HasColumnType("bit");

                    b.Property<string>("Finish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Glow")
                        .HasColumnType("bit");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RemainingWeight")
                        .HasColumnType("float");

                    b.Property<decimal>("SpoolCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("TotalWeight")
                        .HasColumnType("float");

                    b.Property<bool>("Translucent")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spools");
                });

            modelBuilder.Entity("FIM.Server.Models.UserFavoriteFilament", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FilamentId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FilamentId");

                    b.HasIndex("FilamentId");

                    b.ToTable("UserFavoriteFilaments");
                });

            modelBuilder.Entity("FIM.Server.Models.Print", b =>
                {
                    b.HasOne("FIM.Server.Models.Spool", "Spool")
                        .WithMany()
                        .HasForeignKey("SpoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spool");
                });

            modelBuilder.Entity("FIM.Server.Models.UserFavoriteFilament", b =>
                {
                    b.HasOne("FIM.Server.Models.PublicFilamentCatalog", "Filament")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("FilamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filament");
                });

            modelBuilder.Entity("FIM.Server.Models.PublicFilamentCatalog", b =>
                {
                    b.Navigation("FavoritedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
