/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPrints"];
        put?: never;
        post: operations["CreatePrint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Print/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdatePrint"];
        post?: never;
        delete: operations["DeletePrint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Spool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAllSpools"];
        put?: never;
        post: operations["CreateSpool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Spool/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSpoolById"];
        put?: never;
        post?: never;
        delete: operations["DeleteSpool"];
        options?: never;
        head?: never;
        patch: operations["UpdateSpool"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSpoolDto: {
            brand: string;
            material: string;
            color: string;
            /** Format: double */
            diameter: number | string;
            /** Format: double */
            totalWeight: number | string;
            /** Format: double */
            spoolCost: number | string;
        };
        Print: {
            /** Format: int32 */
            id?: number | string;
            name: string;
            /** Format: int32 */
            spoolId: number | string;
            /** Format: double */
            gramsUsed: number | string;
            status: components["schemas"]["PrintStatus"];
            /** Format: date-time */
            createdAt: string;
            spool?: null | components["schemas"]["Spool"];
        };
        PrintStatus: number;
        Spool: {
            /** Format: int32 */
            id?: number | string;
            userId: string;
            brand: string;
            material: string;
            color: string;
            /** Format: double */
            diameter: number | string;
            /** Format: double */
            totalWeight: number | string;
            /** Format: double */
            remainingWeight?: number | string;
            /** Format: double */
            spoolCost: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        SpoolDto: {
            /** Format: int32 */
            id: number | string;
            brand: string;
            material: string;
            color: string;
            /** Format: double */
            diameter: number | string;
            /** Format: double */
            totalWeight: number | string;
            /** Format: double */
            remainingWeight: number | string;
            /** Format: double */
            spoolCost: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateSpoolDto: {
            brand: null | string;
            material: null | string;
            color: null | string;
            /** Format: double */
            diameter: null | number | string;
            /** Format: double */
            totalWeight: null | number | string;
            /** Format: double */
            spoolCost: null | number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetPrints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["Print"][];
                    "application/json": components["schemas"]["Print"][];
                    "text/json": components["schemas"]["Print"][];
                };
            };
        };
    };
    CreatePrint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Print"];
                "text/json": components["schemas"]["Print"];
                "application/*+json": components["schemas"]["Print"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdatePrint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Print"];
                "text/json": components["schemas"]["Print"];
                "application/*+json": components["schemas"]["Print"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeletePrint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAllSpools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["SpoolDto"][];
                    "application/json": components["schemas"]["SpoolDto"][];
                    "text/json": components["schemas"]["SpoolDto"][];
                };
            };
        };
    };
    CreateSpool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpoolDto"];
                "text/json": components["schemas"]["CreateSpoolDto"];
                "application/*+json": components["schemas"]["CreateSpoolDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["SpoolDto"];
                    "application/json": components["schemas"]["SpoolDto"];
                    "text/json": components["schemas"]["SpoolDto"];
                };
            };
        };
    };
    GetSpoolById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["SpoolDto"];
                    "application/json": components["schemas"]["SpoolDto"];
                    "text/json": components["schemas"]["SpoolDto"];
                };
            };
        };
    };
    DeleteSpool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateSpool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSpoolDto"];
                "text/json": components["schemas"]["UpdateSpoolDto"];
                "application/*+json": components["schemas"]["UpdateSpoolDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["SpoolDto"];
                    "application/json": components["schemas"]["SpoolDto"];
                    "text/json": components["schemas"]["SpoolDto"];
                };
            };
        };
    };
}
