/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPrints"];
        put?: never;
        post: operations["CreatePrint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Print/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["DeletePrint"];
        options?: never;
        head?: never;
        patch: operations["UpdatePrint"];
        trace?: never;
    };
    "/Print/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Print/printing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/PublicFilamentCatalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FilamentRecord"][];
                        "application/json": components["schemas"]["FilamentRecord"][];
                        "text/json": components["schemas"]["FilamentRecord"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Spool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAllSpools"];
        put?: never;
        post: operations["CreateSpool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Spool/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSpoolById"];
        put?: never;
        post?: never;
        delete: operations["DeleteSpool"];
        options?: never;
        head?: never;
        patch: operations["UpdateSpool"];
        trace?: never;
    };
    "/Spool/GetLowSpools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/UserFavoriteFilament/SetFavorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    filamentId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/UserFavoriteFilament": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    filamentId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePrintDto: {
            name: string;
            /** Format: int32 */
            spoolId: number | string;
            /** Format: double */
            gramsUsed: number | string;
        };
        CreateSpoolDto: {
            colorHex: null | string;
            colorHexes: null | string[];
            /** Format: int32 */
            extruderTemp: null | number | string;
            /** Format: int32 */
            bedTemp: null | number | string;
            finish: null | string;
            translucent: boolean;
            glow: boolean;
            brand: string;
            material: string;
            colorName: string;
            /** Format: double */
            diameter: number | string;
            /** Format: double */
            totalWeight: number | string;
            /** Format: double */
            spoolCost: number | string;
        };
        FilamentRecord: {
            identifier: string;
            brand: string;
            name: string;
            material: string;
            /** Format: double */
            weight: number | string;
            /** Format: double */
            diameter: number | string;
            colorHex: null | string;
            colorHexes: null | string[];
            /** Format: int32 */
            extruderTemp: null | number | string;
            /** Format: int32 */
            bedTemp: null | number | string;
            finish: null | string;
            translucent: boolean;
            glow: boolean;
        };
        NotificationDto: {
            /** Format: int32 */
            id: number | string;
            message: string;
            type: string;
            isRead: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PrintDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            /** Format: int32 */
            spoolId: number | string;
            /** Format: double */
            gramsUsed: number | string;
            status: components["schemas"]["PrintStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            estimatedEndTime: null | string;
            spool: null | components["schemas"]["Spool"];
        };
        PrintStatus: number;
        Spool: {
            /** Format: int32 */
            id?: number | string;
            userId: string;
            identifier?: string;
            colorName: string;
            colorHex?: null | string;
            colorHexes?: null | string[];
            /** Format: int32 */
            extruderTemp?: null | number | string;
            /** Format: int32 */
            bedTemp?: null | number | string;
            finish?: null | string;
            translucent?: boolean;
            glow?: boolean;
            brand: string;
            material: string;
            /** Format: double */
            diameter: number | string;
            /** Format: double */
            totalWeight: number | string;
            /** Format: double */
            remainingWeight?: number | string;
            /** Format: double */
            spoolCost: number | string;
            /** Format: date-time */
            createdAt: string;
            favorite?: boolean;
        };
        SpoolDto: {
            /** Format: int32 */
            id: number | string;
            identifier: string;
            colorHex: null | string;
            colorHexes: null | string[];
            /** Format: int32 */
            extruderTemp: null | number | string;
            /** Format: int32 */
            bedTemp: null | number | string;
            finish: null | string;
            translucent: boolean;
            glow: boolean;
            brand: string;
            material: string;
            colorName: string;
            /** Format: double */
            diameter: number | string;
            /** Format: double */
            totalWeight: number | string;
            /** Format: double */
            remainingWeight: number | string;
            /** Format: double */
            spoolCost: number | string;
            /** Format: date-time */
            createdAt: string;
            favorite: boolean;
        };
        UpdatePrintDto: {
            name: null | string;
            /** Format: int32 */
            spoolId: null | number | string;
            /** Format: double */
            gramsUsed: null | number | string;
            status: null | components["schemas"]["PrintStatus"];
            /** Format: int32 */
            estimatedMinutes: null | number | string;
        };
        UpdateSpoolDto: {
            identifier: null | string;
            colorHex: null | string;
            colorHexes: null | string[];
            /** Format: int32 */
            extruderTemp: null | number | string;
            /** Format: int32 */
            bedTemp: null | number | string;
            finish: null | string;
            translucent: null | boolean;
            glow: null | boolean;
            brand: null | string;
            material: null | string;
            colorName: null | string;
            /** Format: double */
            diameter: null | number | string;
            /** Format: double */
            totalWeight: null | number | string;
            /** Format: double */
            remainingWeight: null | number | string;
            /** Format: double */
            spoolCost: null | number | string;
            favorite: null | boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["NotificationDto"][];
                    "application/json": components["schemas"]["NotificationDto"][];
                    "text/json": components["schemas"]["NotificationDto"][];
                };
            };
        };
    };
    GetPrints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["PrintDto"][];
                    "application/json": components["schemas"]["PrintDto"][];
                    "text/json": components["schemas"]["PrintDto"][];
                };
            };
        };
    };
    CreatePrint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrintDto"];
                "text/json": components["schemas"]["CreatePrintDto"];
                "application/*+json": components["schemas"]["CreatePrintDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeletePrint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdatePrint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePrintDto"];
                "text/json": components["schemas"]["UpdatePrintDto"];
                "application/*+json": components["schemas"]["UpdatePrintDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAllSpools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["SpoolDto"][];
                    "application/json": components["schemas"]["SpoolDto"][];
                    "text/json": components["schemas"]["SpoolDto"][];
                };
            };
        };
    };
    CreateSpool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpoolDto"];
                "text/json": components["schemas"]["CreateSpoolDto"];
                "application/*+json": components["schemas"]["CreateSpoolDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["SpoolDto"];
                    "application/json": components["schemas"]["SpoolDto"];
                    "text/json": components["schemas"]["SpoolDto"];
                };
            };
        };
    };
    GetSpoolById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["SpoolDto"];
                    "application/json": components["schemas"]["SpoolDto"];
                    "text/json": components["schemas"]["SpoolDto"];
                };
            };
        };
    };
    DeleteSpool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateSpool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSpoolDto"];
                "text/json": components["schemas"]["UpdateSpoolDto"];
                "application/*+json": components["schemas"]["UpdateSpoolDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["SpoolDto"];
                    "application/json": components["schemas"]["SpoolDto"];
                    "text/json": components["schemas"]["SpoolDto"];
                };
            };
        };
    };
}
